# Reddit API credentials
REDDIT_CLIENT_ID = "REDDIT_CLIENT_ID"
REDDIT_CLIENT_SECRET = "REDDIT_CLIENT_SECRET"
REDDIT_USERNAME = "REDDIT_USERNAME"
REDDIT_PASSWORD = "REDDIT_PASSWORD"
USER_AGENT = "reply-timer-bot:v1.0 (by u/SpinningTurt1e)"